---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: golang
    tag: latest

inputs:
- name: spring-auto-reconfiguration-cnb

outputs:
- name: artifactory

caches:
- path: go-module-cache

run:
  path: spring-auto-reconfiguration-cnb/ci/package.sh
